name: CI
on: [push]

jobs:
  # run tests and collect coverage
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage matplotlib
      - name: Test with pytest
        run: coverage run --source=parcoords/ -m pytest ./tests && coverage report -m && coverage xml

  # generate documentation (only on main branch)
  documentation:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install furo
      - name: Build Documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "doc/"
      # upload HTML as artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc/_build/html/

  # deploy documentation to gh-pages (only on main branch)
  deploy:
    needs: documentation
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write # to deploy to Pages
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
